stages:
    - test

image: docker:latest
services:
    - docker:dind
before_script:
    - apk add --no-cache make
    - cp ${API_ENV} ./api/.env
    - cp ${CONSUMER_ENV} ./consumer/.env

test:
    stage: test
    script:
        - docker compose up -d zookeeper kafka-1 kafka-2 kafka-3 kafka-ui database kafka-api kafka-consumer-1 kafka-consumer-2 kafka-consumer-3
        - sleep 20
        - docker container ls
        - docker compose up playwright-test