image: docker:latest
services:
    - docker:dind
before_script:
    - apk add --no-cache make
    - cp ${API_ENV} ./api/.env
    - cp ${CONSUMER_ENV} ./consumer/.env

build-image:
    stage: build
    script:
        - make build

playwright-test:
    stage: test
    before-script:
        - docker compose up -d zookeeper kafka-1 kafka-2 kafka-3 kafka-ui database kafka-api kafka-consumer-1 kafka-consumer-2 kafka-consumer-3
        - sleep 40
        - docker container ls
    script:
        - docker compose up playwright-test