stages:
    - test

image: docker:latest
services:
    - docker:dind
before_script:
    - apk add --no-cache make
    - cp ${API_ENV} ./api/.env
    - cp ${CONSUMER_ENV} ./consumer/.env

test:
    stage: test
    script:
        - make run
        - sleep 20
        - docker logs skill-api-kafka-playwright-test-1